### PR TITLE
CORE:File transfer model.

### PR DESCRIPTION
**Pull request by UlfBj**

### CODE REVIEW

**Comment by UlfBj** [comment]
https://raw.githack.com/UlfBj/vehicle-information-service-specification/filetransfer/spec/VISSv3.0_Core.html

**Comment by UlfBj** [comment]
This PR was presented at the VISS WG meeting where it got some pushback on that the abstraction level did not match the legacy abstraction level in VSS.
My comments to that are the following.
VISS an on a high level be described as an API that enables clients to read or write data related to different vehicle resources. 
The resources are characterized as one of sensor, actuator, or attribute, having defined data types.
I think that a file can quite well be characterized as a vehicle resource, belonging either to the sensor type (read-only), rh the actuator type (read-write).
That the actual file data transfer is handled differently than for legacy signals is in my view not an abstraction level issue.
VSS supports a similar model when it comes to streaming data, https://covesa.github.io/vehicle_signal_specification/rule_set/data_entry/data_types/index.html,
with a control channel and a data channel.
This pattern could possibly be used also for file transfers by referring to common file transfer protocols, but I think there is a value in having it defined in one interface.

**Comment by petervolvowinz** [comment]
Common file transfer protocols like  ftp, sftp, ftps, and scp  have been extensively tested, widely adopted, and optimized over many years. The merit of having one interface for everything can be practical, but also will also make a viss implementation more complex and more difficult to maintain . Should this not then be a PR on VSS first ? Adding file to the VSS tree ?

**Comment by UlfBj** [comment]
This feature should be optional, a client will be able to find out if the server supports it by reading the server capabilities. 
The dependency on VSS from the current solution is that it supports a new datatype "filedescriptor". 
The VSS types are not affected. 
It is preferrable to get it into the VSS data model, but not necessay, compare the "validate" VSS property that is used in VISS but not part of VSS.
I think that VISSv3 should optionally support this solution, but also a solution where a common file transfer protocol is used. For this VSS already has a pattern.

**Pull request merged**
