### PR TITLE
Server capabilities update.

### PR DESCRIPTION
**Pull request by UlfBj**

### CODE REVIEW

**Comment by slawr** [comment]
> https://raw.githack.com/UlfBj/vehicle-information-service-specification/tree/servercapability

This links results in a 404 error for me.

**Comment by slawr** [comment]
It would be good to get some kind of introductory text to these PRs. Even if the link leads to an excellent description it would be good to have a paragraph or two in the PR description to summarise "how the world is changed" by the PR.

**Comment by UlfBj** [comment]
This should hopefully work
https://raw.githack.com/UlfBj/vehicle-information-service-specification/servercapability/spec/VISSv3.0_Core.html

**Comment by petervolvowinz** [comment]
I will merge this.

**Pull request merged**
